# frozen_string_literal: true

begin
    require '/etc/one-appliance/lib/helpers'
rescue LoadError
    require_relative '../lib/helpers'
end

require 'socket'
require 'open3'
require 'rbconfig'
require 'fileutils'
require 'base64'

# Base module for OpenNebula services
module Service

    # SlurmController service implmentation
    module SlurmController

        extend self

        def with_retries(attempts: 10, delay: 15, msg: 'Retrying operation...')
            attempts.times do |i|
                begin
                    return yield
                rescue StandardError => e
                    if i + 1 < attempts
                        msg(:warn, "#{msg} (#{i + 1}/#{attempts}). Error: #{e.message}. Retrying in #{delay}s.")
                        sleep delay
                    else
                        msg(:error, "Operation failed after #{attempts} attempts.")
                        raise e
                    end
                end
            end
        end

        DEPENDS_ON    = []

        def install
            msg :info, 'SlurmController::install'

            # Install dependencies
            bash 'apt update && apt install munge libmunge-dev slurmctld -y'

            # Create slurm.conf
            slurm_conf = <<~CONF
                ClusterName=one
                SlurmctldHost=slurm-one-controller
                AuthType=auth/munge
                ProctrackType=proctrack/cgroup
                SchedulerType=sched/backfill
                SelectType=select/cons_tres

                SlurmUser=slurm
                StateSaveLocation=/var/spool/slurmctld
                SlurmdSpoolDir=/var/spool/slurmd

                SlurmctldPidFile=/var/run/slurm/slurmctld.pid
                SlurmdPidFile=/var/run/slurm/slurmd.pid

                SlurmctldParameters=enable_configless

                MaxNodeCount=100

                Nodeset=one Feature=one

                PartitionName=all  Nodes=ALL Default=yes
            CONF

            File.write('/etc/slurm/slurm.conf', slurm_conf)

            # Create directories and set permissions
            FileUtils.mkdir_p('/var/spool/slurmd')
            FileUtils.mkdir_p('/var/spool/slurmctld')
            FileUtils.chown_R('slurm', 'slurm', '/var/spool/slurmd')
            FileUtils.chown_R('slurm', 'slurm', '/var/spool/slurmctld')
            FileUtils.chmod(0700, '/var/spool/slurmd')
            FileUtils.chmod(0700, '/var/spool/slurmctld')

            # Enable service
            bash 'systemctl enable slurmctld'

            msg :info, 'Installation completed successfully'
        end

        def configure
            msg :info, 'SlurmController::configure'

            #
            # Hostname Management
            #
            desired_hostname = 'slurm-one-controller'
            current_hostname = Socket.gethostname.split('.').first

            if current_hostname != desired_hostname
                msg :info, "Hostname is '#{current_hostname}'," \
                          " changing to '#{desired_hostname}'"
                bash "hostnamectl set-hostname #{desired_hostname}"

                # Update /etc/hosts
                ip = Socket.ip_address_list
                           .find { |a| a.ipv4? && !a.ipv4_loopback? }
                           .ip_address

                hosts_entry = "#{ip}\t#{desired_hostname}"

                unless File.read('/etc/hosts').include?(hosts_entry)
                    msg :info, "Adding '#{hosts_entry}' to /etc/hosts"
                    File.open('/etc/hosts', 'a') { |f| f.puts hosts_entry }
                end
            end

            #
            # Munge Key Management
            #
            munge_key_flag = '/etc/munge/one_key_generated'
            munge_key_path = '/etc/munge/munge.key'

            if !File.exist?(munge_key_flag)
                msg :info, 'Munge key not found or not generated by ONE,' \
                          ' creating a new one.'

                # Backup old key if it exists
                if File.exist?(munge_key_path)
                    timestamp   = Time.now.strftime('%Y%m%d%H%M%S')
                    backup_path = "/etc/munge/munge_old_#{timestamp}.key"
                    msg :info, "Backing up munge key to #{backup_path}"
                    FileUtils.mv(munge_key_path, backup_path)
                end

                # Generate new key, set owner, and create flag file
                bash "mungekey -c -k #{munge_key_path}"
                FileUtils.chown('munge', 'munge', munge_key_path)
                FileUtils.touch(munge_key_flag)

                # Enable and restart munge
                bash 'systemctl enable munge'
                bash 'systemctl restart munge'

                # Verify munge is working
                msg :info, 'Verifying munge service'
                bash 'munge -n | unmunge >/dev/null 2>&1'
                msg :info, 'Munge verification successful'

                # Expose the key to onegate with retries
                with_retries(msg: 'Attempting to update VM data in OneGate...') do
                    msg :info, 'Encoding munge key and updating OneGate'
                    key = Base64.strict_encode64(File.read(munge_key_path))
                    bash "onegate vm update --data MUNGE_KEY_BASE64=#{key}"
                end
                msg :info, 'Successfully updated OneGate with munge key'


                # Restart slurmctld and check
                msg :info, 'Restarting slurmctld'
                bash 'systemctl restart slurmctld'
                bash 'systemctl is-active slurmctld'
                msg :info, 'slurmctld started successfully'
            else
                msg :info, 'Munge key already generated by ONE,' \
                          ' ensuring services are running.'

                # Check if slurmctld is running, restart if not
                begin
                    bash 'systemctl is-active slurmctld'
                    msg :info, 'slurmctld is active.'
                rescue StandardError
                    msg :warn, 'slurmctld is not running,' \
                              ' attempting to restart.'
                    bash 'systemctl restart slurmctld'
                    bash 'systemctl is-active slurmctld'
                    msg :info, 'slurmctld started successfully'
                end
            end

            msg :info, 'Configuration completed successfully'
        end

        def bootstrap
            msg :info, 'SlurmController::bootstrap'
            # No bootstrap actions defined for the controller yet.
            msg :info, 'Bootstrap completed successfully'
        end

    end
end
