# context version definition
VERSION := 6.10.0
RELEASE := 1

# log
VERBOSE         := 1
PACKER_LOG      := 0
PACKER_HEADLESS := true

DISTROS := alma8 alma9 \
           alpine317 alpine318 alpine319 \
           alt10 \
           amazon2 \
           debian11 debian12 \
           devuan4 devuan5 \
           fedora39 fedora40 \
           freebsd13 freebsd14 \
           ol8 ol9 \
           opensuse15 \
           rocky8 rocky9 \
           ubuntu2004 ubuntu2004min ubuntu2204 ubuntu2204min ubuntu2404 ubuntu2404min

SERVICES := service_Wordpress service_VRouter service_OneKE service_OneKEa service_Harbor

.DEFAULT_GOAL := help

# default directories
DIR_BUILD  := build
DIR_EXPORT := export
$(shell mkdir -p ${DIR_BUILD} ${DIR_EXPORT})

# don't delete exported
.SECONDARY: $(patsubst %, $(DIR_EXPORT)/%.qcow2, $(DISTROS)) $(patsubst %, $(DIR_EXPORT)/%.qcow2, $(SERVICES))

.PHONY: context-linux context-windows context-iso help

# this needs to match context-linux/generate-all.sh products
LINUX_CONTEXT_PACKAGES := one-context_${VERSION}-${RELEASE}.deb \
    one-context-${VERSION}-${RELEASE}.el8.noarch.rpm \
    one-context-${VERSION}-${RELEASE}.el9.noarch.rpm \
    one-context-${VERSION}-${RELEASE}.fc.noarch.rpm \
    one-context-${VERSION}-${RELEASE}.suse.noarch.rpm \
    one-context-${VERSION}_${RELEASE}.txz \
    one-context-${VERSION}-alt${RELEASE}.noarch.rpm \
    one-context-${VERSION}-r${RELEASE}.apk \
    one-context-linux-${VERSION}-${RELEASE}.iso

LINUX_CONTEXT_PACKAGES_FULL := $(patsubst %, context-linux/out/%, $(LINUX_CONTEXT_PACKAGES))
CONTEXT_LINUX_SOURCES := $(shell find context-linux/src) context-linux/generate-all.sh  context-linux/generate.sh  context-linux/targets.sh

# this needs to match context-windows/generate-all.sh products
WINDOWS_CONTEXT_PACKAGES := one-context-${VERSION}.msi \
    one-context-${VERSION}.iso

WINDOWS_CONTEXT_PACKAGES_FULL := $(patsubst %, context-windows/out/%, $(WINDOWS_CONTEXT_PACKAGES))
CONTEXT_WINDOWS_SOURCES := $(shell find context-windows/src)

# logging func
INFO=sh -c 'if [ $(VERBOSE) = 1 ]; then  echo [INFO] $$1; fi' INFO

# export all variables
export
