# context version definition
VERSION := 6.10.0
RELEASE := 2

# log
VERBOSE         := 1
PACKER_LOG      := 0
PACKER_HEADLESS := true

DISTROS := alma8 alma9 \
           alpine316 alpine317 alpine318 alpine319 alpine320 \
           alt10 \
           amazon2 amazon2023 \
           debian11 debian12 \
           devuan4 devuan5 \
           fedora38 fedora39 fedora40 \
           freebsd13 freebsd14 \
           ol8 ol9 \
           opensuse15 \
           rocky8 rocky9 \
           ubuntu2004 ubuntu2004min ubuntu2204 ubuntu2204min ubuntu2404 ubuntu2404min \
           windows10Home windows10HomeN windows10HomeSingleLanguage \
           windows10Pro windows10ProN \
           windows10ProWorkstations windows10ProWorkstationsN \
           windows10ProEducation windows10ProEducationN \
           windows10Education windows10EducationN \
           windows10Enterprise windows10EnterpriseN \
           windows10EnterpriseLTSC2015 windows10EnterpriseNLTSC2015 \
           windows10EnterpriseLTSC2016 windows10EnterpriseNLTSC2016 \
           windows10EnterpriseLTSC2019 windows10EnterpriseNLTSC2019 \
           windows10EnterpriseLTSC2021 windows10EnterpriseNLTSC2021 \
           windows11Home windows11HomeN windows11HomeSingleLanguage \
           windows11Pro windows11ProN \
           windows11ProWorkstations windows11ProWorkstationsN \
           windows11ProEducation windows11ProEducationN \
           windows11Education windows11EducationN \
           windows11Enterprise windows11EnterpriseN \
           windows11EnterpriseLTSC2024 windows11EnterpriseNLTSC2024 \
           windows2016Essentials \
           windows2016Standard windows2016StandardCore \
           windows2016Datacenter windows2016DatacenterCore \
           windows2019Essentials \
           windows2019Standard windows2019StandardCore \
           windows2019Datacenter windows2019DatacenterCore \
           windows2022Standard windows2022StandardCore \
           windows2022Datacenter windows2022DatacenterCore \
           windows2025Standard windows2025StandardCore \
           windows2025Datacenter windows2025DatacenterCore \

SERVICES := service_Wordpress service_VRouter service_OneKE service_OneKEa service_Harbor service_MinIO service_example

.DEFAULT_GOAL := help

# default directories
DIR_BUILD  := build
DIR_EXPORT := export
$(shell mkdir -p ${DIR_BUILD} ${DIR_EXPORT})

# don't delete exported
.SECONDARY: $(patsubst %, $(DIR_EXPORT)/%.qcow2, $(DISTROS)) $(patsubst %, $(DIR_EXPORT)/%.qcow2, $(SERVICES))

.PHONY: context-linux context-windows context-iso help

# this needs to match context-linux/generate-all.sh products
LINUX_CONTEXT_PACKAGES := one-context_${VERSION}-${RELEASE}.deb \
    one-context-${VERSION}-${RELEASE}.el8.noarch.rpm \
    one-context-${VERSION}-${RELEASE}.el9.noarch.rpm \
    one-context-${VERSION}-${RELEASE}.fc.noarch.rpm \
    one-context-${VERSION}-${RELEASE}.amzn2.noarch.rpm \
    one-context-${VERSION}-${RELEASE}.amzn2023.noarch.rpm \
    one-context-${VERSION}-${RELEASE}.suse.noarch.rpm \
    one-context-${VERSION}_${RELEASE}.txz \
    one-context-${VERSION}-alt${RELEASE}.noarch.rpm \
    one-context-${VERSION}-r${RELEASE}.apk \
    one-context-linux-${VERSION}-${RELEASE}.iso

LINUX_CONTEXT_PACKAGES_FULL := $(patsubst %, context-linux/out/%, $(LINUX_CONTEXT_PACKAGES))
CONTEXT_LINUX_SOURCES := $(shell find context-linux/src -type f) context-linux/generate-all.sh  context-linux/generate.sh  context-linux/targets.sh

# this needs to match context-windows/generate-all.sh products
WINDOWS_CONTEXT_PACKAGES := one-context-${VERSION}.msi \
    one-context-${VERSION}.iso

WINDOWS_CONTEXT_PACKAGES_FULL := $(patsubst %, context-windows/out/%, $(WINDOWS_CONTEXT_PACKAGES))
CONTEXT_WINDOWS_SOURCES := $(shell find context-windows/src -type f)

# logging func
INFO=sh -c 'if [ $(VERBOSE) = 1 ]; then  echo [INFO] $$1; fi' INFO

# export all variables
export
