# context version definition
VERSION := 6.6.1
RELEASE := 1

# log
VERBOSE            := 1
PACKER_LOG         := 0
PACKER_HEADLESS    := true

DISTROS := alma8 alma9 \
           alpine316 alpine317 alpine318\
           alt9 alt10 \
           amazon2 \
           centos7 centos8stream \
           debian10 debian11 debian12 \
           devuan3 devuan4\
           fedora37 fedora38 \
           freebsd12 freebsd13 \
           ol8 ol9 \
           opensuse15 \
           rocky8 rocky9 \
           ubuntu2004 ubuntu2004min ubuntu2204 ubuntu2204min

SERVICES := service_vnf service_wordpress service_OneKE

.DEFAULT_GOAL := help

# default directories
DIR_BUILD  := build
DIR_EXPORT := export
$(shell mkdir -p ${DIR_BUILD} ${DIR_EXPORT})

# don't delete exported
.SECONDARY: $(patsubst %, $(DIR_EXPORT)/%.qcow2, $(DISTROS)) $(patsubst %, $(DIR_EXPORT)/%.qcow2, $(SERVICES))

.PHONY: context-linux context-windows help

# this needs to match context-linux/generate-all.sh products
LINUX_CONTEXT_PACKAGES := one-context_${VERSION}-${RELEASE}.deb \
    one-context-${VERSION}-${RELEASE}.el6.noarch.rpm \
    one-context-${VERSION}-${RELEASE}.el7.noarch.rpm \
    one-context-${VERSION}-${RELEASE}.el8.noarch.rpm \
    one-context-${VERSION}-${RELEASE}.el9.noarch.rpm \
    one-context-${VERSION}-${RELEASE}.suse.noarch.rpm \
    one-context-${VERSION}_${RELEASE}.txz \
    one-context-${VERSION}-alt${RELEASE}.noarch.rpm \
    one-context-${VERSION}-r${RELEASE}.apk \
    one-context-linux-${VERSION}-${RELEASE}.iso

LINUX_CONTEXT_PACKAGES_FULL := $(patsubst %, context-linux/out/%, $(LINUX_CONTEXT_PACKAGES))

# this needs to match context-windows/generate-all.sh products
WINDOWS_CONTEXT_PACKAGES := one-context-${VERSION}.msi \
    one-context-${VERSION}.iso

WINDOWS_CONTEXT_PACKAGES_FULL := $(patsubst %, context-windows/out/%, $(WINDOWS_CONTEXT_PACKAGES))


# logging func
INFO=sh -c 'if [ $(VERBOSE) = 1 ]; then  echo [INFO] $$1; fi' INFO

# export all variables
export
