#!/usr/bin/env ruby
# ------------------------------------------------------------------------------
# This command gets configuration options from a running oned and outputs it
# in xml format. This is the base defualt configuration for the functionality
# test
#
# This command MUST be run on a clean installation to get the stock default conf
# ------------------------------------------------------------------------------
ONE_LOCATION ||= ENV['ONE_LOCATION']

if !ONE_LOCATION
    RUBY_LIB_LOCATION ||= '/usr/lib/one/ruby'
    GEMS_LOCATION     ||= '/usr/share/one/gems'
else
    RUBY_LIB_LOCATION ||= ONE_LOCATION + '/lib/ruby'
    GEMS_LOCATION     ||= ONE_LOCATION + '/share/gems'
end

if File.directory?(GEMS_LOCATION)
    real_gems_path = File.realpath(GEMS_LOCATION)
    if !defined?(Gem) || Gem.path != [real_gems_path]
        $LOAD_PATH.reject! {|l| l =~ /vendor_ruby/ }
        require 'rubygems'
        Gem.use_paths(real_gems_path)
    end
end

$LOAD_PATH << RUBY_LIB_LOCATION

require 'opennebula'

c   = OpenNebula::Client.new
sys = OpenNebula::System.new(c)

conf = sys.get_configuration
puts conf.to_xml
