AllCops:
  Exclude:
    - '*_spec.rb'

Lint/MissingCopEnableDirective:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
