#!/usr/bin/env bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

set -eo pipefail

USER_DATA="${USER_DATA:-${USERDATA}}"
USER_DATA_ENCODING="${USER_DATA_ENCODING:-${USERDATA_ENCODING}}"

if [ -n "${USER_DATA}" ]; then
    if [ "${USER_DATA_ENCODING}" = "base64" ]; then
        if ! USER_DATA="$(base64 -d <<< "${USER_DATA}" 2>/dev/null)"; then
            echo "Error: Failed base64 decoding of userdata" >&2
            exit 1
        fi
    fi

    one_cloudinit.rb
fi