#!/usr/bin/env bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

if [[ -n "$USER_DATA" ]]; then
    userdata="$USER_DATA"
elif [[ -n "$USERDATA" ]]; then
    userdata="$USERDATA"
fi

if [[ -n "$userdata" ]]; then
    if [[ -n "$USERDATA_ENCODING" ]]; then
        encoding="$USERDATA_ENCODING"
    elif [[ -n "$USER_DATA_ENCODING" ]]; then
        encoding="$USER_DATA_ENCODING"
    fi

    if [[ "$encoding" == "base64" ]]; then
        userdata=$(echo "$userdata" | base64 --decode 2>/dev/null)
        if [[ $? -ne 0 ]]; then
            echo "Warning: Failed base64 decoding of userdata"
        fi
    fi
    
    USER_DATA=$userdata ./one_cloudinit.rb
fi
