#cloud-config
growpart:
  mode: auto
  devices: [/]

users:
  - name: root
    lock_passwd: false
    hashed_passwd: $6$rounds=4096$2RFfXKGPKTcdF.CH$dzLlW9Pg1jbeojxRxEraHwEMAPAbpChBdrMFV1SOa6etSF2CYAe.hC1dRDM1icTOk7M4yhVS1BtwJjah9essD0

disable_root: false
ssh_pwauth:   true

runcmd:
  - perl -i -pe 's/# *PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
  - systemctl reload sshd
