---
name: OneKE
on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'appliances/lib/**'
      - 'appliances/OneKE/**'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - run: gem install rspec
      - run: rspec ./appliances/OneKE/*_spec.rb
